# Generated by Django 5.1.6 on 2025-02-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_area_property_floor_property_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
    ]
