# Generated by Django 5.1.6 on 2025-02-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_property_description_remove_property_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AddField(
            model_name='demand',
            name='max_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='max_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='max_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='max_total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='min_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='min_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='min_total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='max_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='demand',
            name='min_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='demand',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Земля')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
