# Generated by Django 5.1.6 on 2025-02-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_offer_status_demand_max_area_demand_max_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.property'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='max_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='min_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
