# Generated by Django 5.1.6 on 2025-03-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_demand_address_offer_status_alter_demand_max_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_fee', models.PositiveIntegerField()),
                ('buyer_fee', models.PositiveIntegerField()),
                ('company_share', models.PositiveIntegerField()),
                ('realtor_share', models.PositiveIntegerField()),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='api.demand')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='api.offer')),
            ],
        ),
    ]
