# Generated by Django 5.1.6 on 2025-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_demand_fulfilled_offer_fulfilled_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='buyer_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='company_share',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='realtor_share',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
